[package]
name = "block-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
askama = "0.12.1"
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive"] }
sqlx = "0.7.4"
thiserror = "1.0.61"
tokio = "1.37.0"
